export const USERS_SEARCH_REQUEST = "USERS_SEARCH_REQUEST";
export const USERS_SEARCH_SUCCESS = "USERS_SEARCH_SUCCESS";
export const USERS_SEARCH_FAIL = "USERS_SEARCH_FAIL";
export const USERS_SEARCH_CLEAR = "USERS_SEARCH_CLEAR";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
